# Project pages
pages:
    - Install: index.md
#    - About: about.md
    - Component:
        - Avatar: Avatar.md
# Project information
site_name: 'Material Elements'
site_description: 'A Material Design for React Native'
site_author: 'react-native-studio'
site_url: 'https://react-native-studio.github.io/material-elements/'

# Repository
repo_name: 'material-elements'
repo_url: 'https://github.com/react-native-studio/material-elements'
docs_dir: '../material-elements/docs'
# Copyright
copyright: 'Copyright &copy; 2017 - 2018 Lmy'

# Configuration
theme:
  name: 'material'
  custom_dir: 'theme'
  language: 'zh'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature:
      tabs: false

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/react-native-studio'

# Google Analytics
google_analytics:
  - 'UA-XXXXXXXX-X'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
